### ISSUE TITLE
Incorporate webpack settings for sass by default

### ISSUE THREAD

**Issue by brittanystoroz** [turingschool-examples/gametime-starter#109]
Or maybe we just want to add these to the README in case people want to use it

**Comment by robbiejaeger** [comment]
We'll leave this out of the standard boilerplate, but these are the instructions for enabling sass:

1. Change the `base.css` file to be `base.scss` (all style files should have the scss extension now)
2. Change the `index.js` style import to match the new file name: `import './css/base.scss';`
3. Run the command `npm install sass-loader node-sass webpack --save-dev` in your terminal from within your project directory
4. Change the `webpack.config.js` content to:

```json
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'main.bundle.js'
  },
  devtool: 'inline-source-map',
  mode: 'development',
  // CSS and file (image) loaders
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: ['style-loader', 'css-loader', 'sass-loader'],
      },
      {
        test: /\.(png|svg|jpg|gif)$/,
        use: [
              {
                loader: 'file-loader',
                options: {
                  name: '[name].[ext]',
                  outputPath: 'images/',
                  publicPath: 'images/'
                }
              }
            ]
      }
    ],
  },
  // Below is needed for webpack-dev-server
  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.html'
    })
  ],
  devServer: {
         contentBase: './dist'
  }
};
```

**Comment by robbiejaeger** [comment]
Added this functionality in this commit: https://github.com/turingschool-examples/gametime-starter/commit/9fab900bcd11ed94cae7c8b08377cb9fe8a4862b

Since the project is later in the mod, they are expected to use SASS/SCSS, which is why we put it in by default now.
